import { StyleSheet } from 'react-native'

export const globalStyles = StyleSheet.create({
    container: {
        justifyContent: 'center',
        alignItems: 'center',
        height: '60%',
        backgroundColor: '#ffc845',
        borderTopLeftRadius: 100,
        borderTopRightRadius: 100,
    },
    bg: {
        backgroundColor: '#f2f6fa',
        height: '100%',
    },
    titleText: {
        fontFamily: 'ralewayBold',
        fontSize: 28,
        textAlign: 'center',
        marginTop: '4%',
        color: 'black',
    },
    studentDetailsText: {
        padding: '5%',
        fontFamily: 'ralewayRegular',
        fontSize: 21,
        color: 'black',
    },
    studentListText: {
        fontFamily: 'ralewayBold',
        fontSize: 30,
        color: 'black',
        textAlign: 'center',
        marginTop: '5%',
    },
    aContainer: {
        height: '100%',
    },
    detailsContainer: {
        margin: 15,
        alignContent: 'center',
        justifyContent: 'center',
        height: '50%',
        backgroundColor: '#d7d7d8',
        borderRadius: 100,
    },
    button: {
        backgroundColor: '#45c8ff',
        borderRadius: 40,
        height: '65%',
        width: '83%',
        alignSelf: 'center',
    },
    buttonText: {
        color: 'black',
    },
    circleButton: {
        marginBottom: '50%',
        height: 75,
        width: 75,
        borderRadius: 100,
        backgroundColor: '#45c8ff',
        alignSelf: 'center',
        justifyContent: 'center',
    },
    listIcon: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    centerContent: {
        marginTop: '75%',
        alignSelf: 'center',
    },
    padding: {
        paddingBottom: 50,
        height: 130,
    },
    logo: {
        marginTop: 10,
        width: '100%',
        height: '55%',
    },
    pushUp: {
        justifyContent: 'center',
        marginTop: 40,
    },
    simpleInput: {
        backgroundColor: '#c4dff6',
        borderColor: 'black',
        borderWidth: 1.5,
        width: 200,
        padding: 11,
        marginTop: 13,
        borderRadius: 10,
        alignSelf: 'center',
    },
    goalInput: {
        backgroundColor: '#c4dff6',
        borderColor: 'black',
        borderWidth: 1.5,
        width: 250,
        height: 130,
        padding: 10,
        marginTop: 13,
        borderRadius: 10,
    },
    addButton: {
        marginTop: 10,
        alignSelf: 'center',
        backgroundColor: '#7fbb00',
        borderRadius: 100,
        height: 50,
        width: '30%',
    },
    footer: {
        width: '100%',
        height: '33%',
        backgroundColor: '#ffc845',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        bottom: 0,
        borderTopLeftRadius: 100,
        borderTopRightRadius: 100,
        // borderRadius: 55,
    },
    footerText: {
        marginTop: '7%',
        marginBottom: '7%',
        fontFamily: 'ralewayBold',
        fontSize: 28,
        textAlign: 'center',
        textDecorationLine: 'none',
        color: 'black',
    },
})